/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BarbersIdRouteImport } from './routes/barbers.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as AuthenticatedAdminStylesRouteImport } from './routes/_authenticated/admin/styles'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminRegisterRouteImport } from './routes/_authenticated/admin/register'
import { Route as AuthenticatedAdminBusinessRouteImport } from './routes/_authenticated/admin/business'
import { Route as AuthenticatedAdminBarbersRouteImport } from './routes/_authenticated/admin/barbers'
import { Route as AuthenticatedAdminAppointmentsRouteImport } from './routes/_authenticated/admin/appointments'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersIdRoute = BarbersIdRouteImport.update({
  id: '/barbers/$id',
  path: '/barbers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminStylesRoute =
  AuthenticatedAdminStylesRouteImport.update({
    id: '/styles',
    path: '/styles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRegisterRoute =
  AuthenticatedAdminRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBusinessRoute =
  AuthenticatedAdminBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBarbersRoute =
  AuthenticatedAdminBarbersRouteImport.update({
    id: '/barbers',
    path: '/barbers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppointmentsRoute =
  AuthenticatedAdminAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/barbers/$id': typeof BarbersIdRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/barbers': typeof AuthenticatedAdminBarbersRoute
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/register': typeof AuthenticatedAdminRegisterRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/barbers/$id': typeof BarbersIdRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/admin/barbers': typeof AuthenticatedAdminBarbersRoute
  '/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/admin/register': typeof AuthenticatedAdminRegisterRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/book': typeof BookRoute
  '/login': typeof LoginRoute
  '/reviews': typeof ReviewsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/barbers/$id': typeof BarbersIdRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/appointments': typeof AuthenticatedAdminAppointmentsRoute
  '/_authenticated/admin/barbers': typeof AuthenticatedAdminBarbersRoute
  '/_authenticated/admin/business': typeof AuthenticatedAdminBusinessRoute
  '/_authenticated/admin/register': typeof AuthenticatedAdminRegisterRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/styles': typeof AuthenticatedAdminStylesRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/login'
    | '/reviews'
    | '/admin'
    | '/barbers/$id'
    | '/admin/admins'
    | '/admin/appointments'
    | '/admin/barbers'
    | '/admin/business'
    | '/admin/register'
    | '/admin/reviews'
    | '/admin/styles'
    | '/api/public/bootstrap-admin'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/login'
    | '/reviews'
    | '/barbers/$id'
    | '/admin/admins'
    | '/admin/appointments'
    | '/admin/barbers'
    | '/admin/business'
    | '/admin/register'
    | '/admin/reviews'
    | '/admin/styles'
    | '/api/public/bootstrap-admin'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/book'
    | '/login'
    | '/reviews'
    | '/_authenticated/admin'
    | '/barbers/$id'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/appointments'
    | '/_authenticated/admin/barbers'
    | '/_authenticated/admin/business'
    | '/_authenticated/admin/register'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/styles'
    | '/api/public/bootstrap-admin'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BookRoute: typeof BookRoute
  LoginRoute: typeof LoginRoute
  ReviewsRoute: typeof ReviewsRoute
  BarbersIdRoute: typeof BarbersIdRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers/$id': {
      id: '/barbers/$id'
      path: '/barbers/$id'
      fullPath: '/barbers/$id'
      preLoaderRoute: typeof BarbersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/styles': {
      id: '/_authenticated/admin/styles'
      path: '/styles'
      fullPath: '/admin/styles'
      preLoaderRoute: typeof AuthenticatedAdminStylesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/register': {
      id: '/_authenticated/admin/register'
      path: '/register'
      fullPath: '/admin/register'
      preLoaderRoute: typeof AuthenticatedAdminRegisterRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/business': {
      id: '/_authenticated/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AuthenticatedAdminBusinessRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/barbers': {
      id: '/_authenticated/admin/barbers'
      path: '/barbers'
      fullPath: '/admin/barbers'
      preLoaderRoute: typeof AuthenticatedAdminBarbersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/appointments': {
      id: '/_authenticated/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AuthenticatedAdminAppointmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAppointmentsRoute: typeof AuthenticatedAdminAppointmentsRoute
  AuthenticatedAdminBarbersRoute: typeof AuthenticatedAdminBarbersRoute
  AuthenticatedAdminBusinessRoute: typeof AuthenticatedAdminBusinessRoute
  AuthenticatedAdminRegisterRoute: typeof AuthenticatedAdminRegisterRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminStylesRoute: typeof AuthenticatedAdminStylesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAppointmentsRoute: AuthenticatedAdminAppointmentsRoute,
  AuthenticatedAdminBarbersRoute: AuthenticatedAdminBarbersRoute,
  AuthenticatedAdminBusinessRoute: AuthenticatedAdminBusinessRoute,
  AuthenticatedAdminRegisterRoute: AuthenticatedAdminRegisterRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminStylesRoute: AuthenticatedAdminStylesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BookRoute: BookRoute,
  LoginRoute: LoginRoute,
  ReviewsRoute: ReviewsRoute,
  BarbersIdRoute: BarbersIdRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
